CREATE TABLE users (
    uid INT AUTO_INCREMENT PRIMARY KEY, 
    fname VARCHAR (100) NOT NULL, 
    lname VARCHAR (100) NOT NULL, 
    email VARCHAR (100) NOT NULL, 
    password VARCHAR (100) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);